format = """$os$username$hostname$directory$git_branch$git_status\n❯ """
right_format = """$cmd_duration$time$battery"""

[os]
format = '[$symbol](bold white) '

[os.symbols]
Macos = " "

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) '
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold white) '

[directory]
truncation_length = 5
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = 'red'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
style = 'bold green'

[git_status]
format = '([ $all_status$ahead_behind]($style) )'
style = 'bold green'
conflicted = '[ conflicted=${count}](red) '
up_to_date = '[󰘽 up-to-date](green) '
untracked = '[󰋗 untracked=${count}](red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 modified=${count}](yellow) '
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '

[cmd_duration]
show_milliseconds = true
min_time = 1
format = 'took [$duration](bold white) '

[time]
disabled = false
format = '[at $time ](bold white)'
time_format = '%T'

[battery]
full_symbol = '󰁹'
charging_symbol = '󰂄'
discharging_symbol = '󰂃'
format = '| [$symbol $percentage]($style)'

[[battery.display]]
threshold = 20
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[[battery.display]]
threshold = 100
style = 'bold green'
